name: CD - Build & Push Docker Image

on:
  push:
    branches:
      - dev  # Trigger khi push vào main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                   # Đường dẫn tới Dockerfile (tùy theo dự án của bạn)
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spmss:latest
