name: CD - Build & Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spmss:latest

  deploy-backend:
    runs-on: self-hosted
    needs: build-and-push
    env:
      GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Stop and remove old containers
        run: |
          docker compose -p backend-gsu25se47 down --remove-orphans || true

      - name: Remove old images
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/spmss:latest || true

      - name: Cleanup dangling images
        run: docker image prune -f

      - name: Pull Image And Deploy From VPS
        run: docker compose -p backend-gsu25se47 up -d --pull always


